{"timestamp":"2025-07-03T19:26:19.775596","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-03T19:26:19.776260","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/basicDag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-03T19:26:20.043109","level":"info","event":"Spinning up container for /opt/airflow/config/tropo-objects/example-tropo-1.rtf","logger":"root"}
{"timestamp":"2025-07-03T19:26:20.190556","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"APIError","exc_value":"500 Server Error for http+docker://localhost/v1.49/containers/b88bc2c8d791ade407522893e0c943041935c91edbdf9fb7fbd731b56c6698c2/start: Internal Server Error (\"Mounts denied: \nThe path /opt/airflow/config/runconfigs/example-tropo-1 is not shared from the host and is not known to Docker.\nYou can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.\nSee https://docs.docker.com/desktop/settings/mac/#file-sharing for more info.\")","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/basicDag.py","lineno":178,"name":"spinup_workers"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/docker/models/containers.py","lineno":883,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/docker/models/containers.py","lineno":420,"name":"start"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/docker/utils/decorators.py","lineno":19,"name":"wrapped"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py","lineno":1136,"name":"start"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py","lineno":277,"name":"_raise_for_status"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py","lineno":39,"name":"create_api_error_from_http_exception"}],"is_group":false,"exceptions":[]},{"exc_type":"HTTPError","exc_value":"500 Server Error: Internal Server Error for url: http+docker://localhost/v1.49/containers/b88bc2c8d791ade407522893e0c943041935c91edbdf9fb7fbd731b56c6698c2/start","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py","lineno":275,"name":"_raise_for_status"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/models.py","lineno":1024,"name":"raise_for_status"}],"is_group":false,"exceptions":[]}]}
